name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up locale to Japanese
        run: |
          sudo apt-get update
          sudo apt-get install -y language-pack-ja
          sudo locale-gen ja_JP.UTF-8
          sudo update-locale LANG=ja_JP.UTF-8
          export LANG=ja_JP.UTF-8
          export LC_ALL=ja_JP.UTF-8
          echo "Locale is set to $LANG"
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - uses: pnpm/action-setup@v4
        with:
          version: 8
      - run: pnpm install
      - name: Run client test
        run: pnpm --filter './apps/client' run test

  deploy:
    uses: ./.github/workflows/server-deploy.yml
