name: Deploy Server
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: actions/checkout@v4

      - name: "set up wrangler.toml"
        env:
          DATABASE_NAME: ${{ secrets.D1_DATABASE_NAME }}
          DATABASE_ID: ${{ secrets.D1_DATABASE_ID }}
        run: |
          echo "[[d1_databases]]" >> ./apps/server/wrangler.toml
          echo "binding = \"DB\"" >> ./apps/server/wrangler.toml
          echo "database_name = \"${DATABASE_NAME}\"" >> ./apps/server/wrangler.toml
          echo "database_id = \"${DATABASE_ID}\"" >> ./apps/server/wrangler.toml
          echo "migrations_dir = \"./infra/migrations/\"" >> ./apps/server/wrangler.toml
          cat ./apps/server/wrangler.toml

      - name: Deploy app
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          packageManager: pnpm
          workingDirectory: apps/server
